import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#ffffff',
    },
    backgroundGradient: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
    },
    gradientCircle1: {
        position: 'absolute',
        top: -100,
        right: -100,
        width: 200,
        height: 200,
        borderRadius: 100,
        backgroundColor: '#4f46e5',
        opacity: 0.1,
    },
    gradientCircle2: {
        position: 'absolute',
        top: 200,
        left: -50,
        width: 150,
        height: 150,
        borderRadius: 75,
        backgroundColor: '#7c3aed',
        opacity: 0.08,
    },
    gradientCircle3: {
        position: 'absolute',
        bottom: 100,
        right: -80,
        width: 160,
        height: 160,
        borderRadius: 80,
        backgroundColor: '#06b6d4',
        opacity: 0.06,
    },
    keyboardView: {
        flex: 1,
    },
    scrollContent: {
        flexGrow: 1,
        paddingHorizontal: 24,
    },
    header: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        minHeight: 200,
    },
    logoContainer: {
        alignItems: 'center',
    },
    logoBackground: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: '#4f46e5',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 16,
        shadowColor: '#4f46e5',
        shadowOffset: {
            width: 0,
            height: 8,
        },
        shadowOpacity: 0.3,
        shadowRadius: 16,
        elevation: 12,
    },
    logoIcon: {
        fontSize: 32,
    },
    logo: {
        fontSize: 36,
        fontWeight: 'bold',
        color: '#1e293b',
        marginBottom: 8,
    },
    tagline: {
        fontSize: 16,
        color: '#64748b',
        fontWeight: '500',
    },
    formContainer: {
        flex: 1,
        justifyContent: 'center',
        paddingBottom: 40,
    },
    welcomeSection: {
        marginBottom: 32,
    },
    welcomeText: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#1e293b',
        marginBottom: 8,
    },
    subtitleText: {
        fontSize: 16,
        color: '#64748b',
    },
    inputContainer: {
        marginBottom: 20,
    },
    inputLabelContainer: {
        marginBottom: 8,
    },
    inputLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#374151',
    },
    inputWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#ffffff',
        borderRadius: 16,
        paddingHorizontal: 16,
        paddingVertical: 4,
        borderWidth: 2,
        borderColor: '#e5e7eb',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 3,
    },
    inputIcon: {
        fontSize: 18,
        marginRight: 12,
    },
    textInput: {
        flex: 1,
        paddingVertical: 16,
        fontSize: 16,
        color: '#1f2937',
    },
    eyeButton: {
        padding: 8,
    },
    eyeButtonText: {
        fontSize: 20,
    },
    forgotPasswordContainer: {
        alignSelf: 'flex-end',
        marginBottom: 24,
    },
    forgotPasswordText: {
        fontSize: 14,
        color: '#4f46e5',
        fontWeight: '600',
    },
    loginButton: {
        backgroundColor: '#4f46e5',
        borderRadius: 16,
        paddingVertical: 18,
        alignItems: 'center',
        marginBottom: 24,
        shadowColor: '#4f46e5',
        shadowOffset: {
            width: 0,
            height: 6,
        },
        shadowOpacity: 0.3,
        shadowRadius: 12,
        elevation: 10,
        flexDirection: 'row',
        justifyContent: 'center',
    },
    loginButtonDisabled: {
        backgroundColor: '#9ca3af',
    },
    loginButtonText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#ffffff',
    },
    loadingSpinner: {
        width: 16,
        height: 16,
        borderRadius: 8,
        borderWidth: 2,
        borderColor: '#ffffff',
        borderTopColor: 'transparent',
        marginLeft: 8,
    },
    socialLoginSection: {
        marginBottom: 24,
    },
    dividerContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 20,
    },
    divider: {
        flex: 1,
        height: 1,
        backgroundColor: '#e5e7eb',
    },
    dividerText: {
        marginHorizontal: 16,
        fontSize: 14,
        color: '#9ca3af',
        fontWeight: '500',
    },
    socialButtonsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 12,
    },
    socialButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#ffffff',
        borderRadius: 12,
        paddingVertical: 14,
        paddingHorizontal: 16,
        borderWidth: 1,
        borderColor: '#e5e7eb',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    socialButtonIcon: {
        fontSize: 18,
        marginRight: 8,
    },
    socialButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#374151',
    },
    signUpContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    signUpText: {
        fontSize: 14,
        color: '#64748b',
    },
    signUpLink: {
        fontSize: 14,
        color: '#4f46e5',
        fontWeight: 'bold',
    },
});
